version: "3.8"

services:
  backend:
    image: openjdk:17
    container_name: springboot-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: sh -c "java -jar target/*.jar"
